In [1]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [3]:
import numpy as np
array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [11]:
import numpy as np
array_zeros = np.zeros((3, 4))
print(array_zeros)
array_ones = np.ones((3, 4))
print(array_ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
import numpy as np
array_full = np.full((3,3),7)
print(array_full)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [15]:
import numpy as np
arr = np.arange(20),reshape(5,4)
print(arr[:,:])




TypeError: list indices must be integers or slices, not tuple