In [1]:
# indexing of an array 
import numpy as np
a=np.array1=([[[1,2,3,4],[5,6,7,8],[4,7,8,3]],
               [[1,2,3,4],[1,4,6,8],[8,6,7,3]],
               [[7,4,5,6],[3,4,1,2],[6,7,3,4]]])

b=([[[1,2,3,4],[5,6,7,8],[4,7,8,3]],
               [[1,2,3,4],[1,4,6,8],[8,6,7,3]],
               [[7,4,5,6],[3,4,1,2],[6,7,3,4]]])
print(a+b)

[[[1, 2, 3, 4], [5, 6, 7, 8], [4, 7, 8, 3]], [[1, 2, 3, 4], [1, 4, 6, 8], [8, 6, 7, 3]], [[7, 4, 5, 6], [3, 4, 1, 2], [6, 7, 3, 4]], [[1, 2, 3, 4], [5, 6, 7, 8], [4, 7, 8, 3]], [[1, 2, 3, 4], [1, 4, 6, 8], [8, 6, 7, 3]], [[7, 4, 5, 6], [3, 4, 1, 2], [6, 7, 3, 4]]]


In [5]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_array)


[1 2 3 4 5]


In [11]:
import numpy as np
my_array = np.array ([1, 2, 3, 4, 5])
print(my_array.shape) 
my_array = np.array ([[1, 2, 3], [4, 5, 6]])
print(my_array.shape)  
my_array = np.array ([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(my_array.shape)  

(5,)
(2, 3)
(2, 2, 3)


In [13]:
import numpy as np
my_array = np.array([[1, 2, 3], [4, 5, 6]])

print(my_array.strides) 

(12, 4)


In [19]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr3 = np.array([[[1, 2, 3],
                  [4, 5, 6]],
                 [[7, 8, 9],
                  [10, 11, 12]]])
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Array 3:\n", arr3)
print("Number of dimensions in Array 1:", arr1.ndim)
print("Number of dimensions in Array 2:", arr2.ndim)
print("Number of dimensions in Array 3:", arr3.ndim)

Array 1:
 [1 2 3 4 5]
Array 2:
 [[1 2 3]
 [4 5 6]]
Array 3:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Number of dimensions in Array 1: 1
Number of dimensions in Array 2: 2
Number of dimensions in Array 3: 3


In [25]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
num_elements = array.size
print("Number of elements in the array:", num_elements)

Number of elements in the array: 6


In [27]:
import numpy as np

array = np.array([1, 2, 3, 4], dtype=np.int32)

element_size = array.itemsize

print(f"Size of each element: {element_size} bytes")

Size of each element: 4 bytes


In [29]:
import numpy as np

base_array = np.array([1, 2, 3, 4])

view_array = base_array[1:3]

print("Base array of view_array:", view_array.base)
print("Base array of base_array:", base_array.base)  # This should print None

Base array of view_array: [1 2 3 4]
Base array of base_array: None


In [31]:
import numpy as np

array = np.array([1, 2, 3, 4], dtype=np.int32
                
total_bytes = array.nbytes

print(f"Total bytes consumed by the array: {total_bytes} bytes")

Total bytes consumed by the array: 16 bytes
